name: SimpleeFood Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      RACK_ENV: test
      RUNNING_ON_CI_SERVER: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Set up Node 18.20.7
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.7
          # does _not_ run `yarn install`, but _does_ install `yarn`
          cache: yarn

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Run Unit Specs (excluding JS)
        run: bundle exec rspec --tag ~type:feature

  headless_browser_tests:
    name: Headless Browser Tests
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99.0
      RACK_ENV: test
      RUNNING_ON_CI_SERVER: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Set up Node 18.20.7
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.7
          # does _not_ run `yarn install`, but _does_ install `yarn`
          cache: yarn

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Start xvfb for headless browser support
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run JS Specs
        run: bundle exec rspec --tag type:feature

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Set up Node 18.20.7
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.7
          # does _not_ run `yarn install`, but _does_ install `yarn`
          cache: yarn

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Run Stylelint
        run: npx stylelint app/frontend/stylesheets/*

      - name: Run Prettier
        run: npx prettier --check --config .prettierrc.json '**/*'

  build_eligibility:
    name: Determine Build Eligibility
    runs-on: ubuntu-latest
    needs: [unit_tests, headless_browser_tests]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.unit_tests.result == 'success' &&
      needs.headless_browser_tests.result == 'success'

    outputs:
      run_docker_build: ${{ steps.check_if_tag_exists.outputs.run_docker_build }}
      docker_version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from CHANGELOG
        id: version
        run: |
          version=$(cat CHANGELOG.md | grep -P '^## v' | head -n1 | grep -oP '\d+\.\d+\.\d+')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if git tag already exists
        id: check_if_tag_exists
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.version.outputs.version }} already exists."
            echo "run_docker_build=false" >> $GITHUB_OUTPUT
          else
            echo "Tag v${{ steps.version.outputs.version }} does not exist."
            echo "run_docker_build=true" >> $GITHUB_OUTPUT
          fi

  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build_eligibility
    if: needs.build_eligibility.run_docker_build == 'true'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            abhchand/simplee_food:v${{ needs.build_eligibility.docker_version }}
            abhchand/simplee_food:latest

      - name: Output pushed image digest
        run: "echo \"Digest: ${{ steps.docker_build.outputs.digest }}\""

      - name: Create and push Git tag
        run: |
          echo "Creating Tag v${{ needs.build_eligibility.docker_version }}"
          git tag v${{ needs.build_eligibility.docker_version }}
          git push origin v${{ needs.build_eligibility.docker_version }}
